### PR TITLE
Added an entry for Secure Code Warrior

### PR DESCRIPTION
**Pull request by jksdua**
Added a table row for Secure Code Warrior platform. Secure Code Warrior is an Australian security startup with a secure coding platform for developers.

### CODE REVIEW

**Comment by joe-shenouda** [comment]
"The requested page could not be found" site will not be added

**Comment by jksdua** [comment]
Hi Joe,

Can you please check again? You should see something similar to the below screenshot:

image

**Comment by joe-shenouda** [comment]
The site seems to work now. What I've seen that the site needs an invite code: "Please enter your invitation token here. If you do not have one, please contact your manager or your Secure Code Warrior representative."

The site does not seem to be free or easily accessible for anyone to jump in and start training using the full website's resources.

**Comment by jksdua** [comment]
There are two sections on the website. The one I've linked is a list of curated resources available for free without any registration. We don't ask users to provide any personal information to access this section, it's completely free of cost. These are training videos or slides that explain the fundamentals of security vulnerabilities.

Users can subscribe to the paid version of the website through securecodewarrior.com. This unlocks hands-on exercises. There is a 14-day free trial available on securecodewarrior.com.

**Comment by joe-shenouda** [comment]
I like to list 100% free resources only that are directly accessible without unlocks.

**Pull request closed without merging**
